#define kDiosBaseUrl                @"http://prar.prometsource.com/"
#define kDiosBaseNode               @"ar_object"
#define kDiosEndpoint               @"prar"

#define kDiosBaseComment            @"comment"
#define kDiosBaseUser               @"user"
#define kDiosBaseFile               @"file"
#define kDiosBaseView               @"views"
#define kDiosBaseTaxonmyTerm        @"taxonomy_term"
#define kDiosBaseTaxonmyVocabulary  @"taxonomy_vocabulary"
